version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: postor/webmock-base
    environment:
      HOST: 0.0.0.0 
      YPERSISTENCE: db-files 
      PORT: 1234
    volumes:
      - db_data:/app/db/db-files
    ports:
      - "1234:1234"
    command: npm run -w db ywebsocket

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: postor/webmock-base
    environment:
      WS_TINYBASE: "ws://db:1234"
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: npm -w backend run start

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: postor/webmock-base
    environment:
      WS_TINYBASE: "ws://127.0.0.1:1234"
    depends_on:
      - backend
    ports:
      - "3020:3020"
    command: npm -w frontend run start

volumes:
  db_data:

